# docker-compose.yml

version: '3.3'
services:
  postgres:
    image: postgres:13.5
    restart: always
    env_file:
      - /.env
    ports:
      - '5432:5432'

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - /.env
    ports:
      - '15432:80'
